### ISSUE TITLE
<note> missing from dbReader.xsl Template

### ISSUE THREAD

**Issue by lakeward** [jmourelos/doconv#3]
Thanks for this utility. I believe the &lt;note> element needs to be added to the following template in dbReader.xsl.

&lt;!-- TO DO: MAY NEED TO DISTINGUISH section -->
&lt;xsl:template match="*" mode="topic.body.content.in">
 &lt;xsl:apply-templates select="ackno|address|anchor|annotation|
            bibliolist|blockquote|bridgehead|calloutlist|caution|classsynopsis|
            cmdsynopsis|constraintdef|constructorsynopsis|destructorsynopsis|
            epigraph|equation|example|fieldsynopsis|figure|formalpara|
            funcsynopsis|glosslist|important|indexterm|informalequation|
            informalexample|informalfigure|informaltable|itemizedlist|
            literallayout|mediaobject|methodsynopsis|orderedlist|
            para|procedure|productionset|programlisting|
            programlistingco|remark|revhistory|screen|screenco|
            screenshot|segmentedlist|sidebar|simpara|simplelist|synopsis|
            table|tip|variablelist|warning"
        mode="topic.body.child"/>
&lt;/xsl:template>

**Comment by jmourelos** [comment]
Hi, thanks a lot for the feedback. Probably you are right about the missing element, could you provide any document containing the <note> element to compare the conversion before and after your proposed change?

**Comment by lakeward** [comment]
Here is a test file that exercises the admonitions. I changed the extension so that it could be uploaded to github

[Admonition.adoc.txt](https://github.com/jmourelos/doconv/files/519766/Admonition.adoc.txt)

**Comment by jmourelos** [comment]
Thanks for your time, I will release soon a new version with the fix.

**Comment by lakeward** [comment]
Sounds good. Thanks


________________________________
