### ISSUE TITLE
Error: object of type 'dictionary-keyiterator' has no len()

### ISSUE THREAD

**Issue by wbrisett** [jmourelos/doconv#4]
I'm not exactly sure why, but when I try to use doconv, I'm seeing this error:

doconv convert /Users/waybri01/Downloads/asciidoc.txt asciidoc dita
Error: object of type 'dictionary-keyiterator' has no len()

I'm on Mac OS X, with:
asciidoc : 8.6.10
doconv: 0.1.6

Any ideas?

**Comment by jmourelos** [comment]
Thanks a lot for the feedback! Yes, I just installed doconv from scratch and I experienced the same problem.

I will try to fix it and release a new version this weekend.

**Comment by jmourelos** [comment]
I took a quick look and it seems to be a problem with one of the dependencies.

As a workaround until a release a new version, you can downgrade the dependency 'networkx':

`pip install networkx==1.8.1`

**Comment by wbrisett** [comment]
Thanks that worked.
